# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a34c79515d2408b59f4036b3b8ccd919"
name = "final-price-lock-ui"
application_url = "https://final-price-lock-ui.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"  

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://final-price-lock-ui.onrender.com/auth/callback",
  "https://final-price-lock-ui.onrender.com/auth/shopify/callback",
  "https://final-price-lock-ui.onrender.com/api/auth/callback"
]
